### PR TITLE
Links (meaning in-game items and other certain keywords) are now blue…

### PR DESCRIPTION
**Pull request by deatrys**
….  also has another option inside templates/ directory called 'original.xml' which is the original Tillmen generated version (but with twice-high thoughts panel)

### CODE REVIEW

**Comment by deatrys** [comment]
Note that the **:priority** value for a highlight is sorted correctly with lower values taking precedence, so the value of "2" for the blue links is the least

**Comment by deatrys** [comment]
Also, the change for **sort_by** using **or** probably the **or** doesn't really do anything, i had it that way because i was using priority of 0 or 1 and i figured if it was 0 it would roll over to the other part....  i like to leave it in, in case it happens to do what i want it to.. so far i've not seen any issue with how it runs, but I also don't have any highlights of shorter length than others over the same phrase

**Comment by deatrys** [comment]
this code change is stable for me, been using it for a week flawlessly.  the only issue others might find is if short-length highlights are not properly taking precedence over longer ones.  i've had no issues

**Comment by deatrys** [comment]
I don't still visit Elanthia, but this change is sharp, makes keywords blue for names/items/etc., if you want to look into it.

**Comment by h6b45** [comment]
Please close this Pull Request because a new one is online for the most recent release version.

Thank you.

**Comment by mrhoribu** [comment]
> Please close this Pull Request because a new one is online for the most recent release version.
> 
> Thank you.

This PR is still valid, just it was never commented on for feasibility and expansion.

**Comment by mrhoribu** [comment]
> I don't still visit Elanthia, but this change is sharp, makes keywords blue for names/items/etc., if you want to look into it.

@deatrys This PR looks great, I only have a few concerns. One is to make this something that can be enabled or disabled based on perhaps a launch flag of profanity? As not everyone wants to run their FE with links shown. Also, any way to perhaps make it so the link color is not hardcoded and can be set via the XML?

**Comment by mrhoribu** [comment]
Resolved via #9

**Pull request closed without merging**
